### ISSUE TITLE
Reproducing human study

### ISSUE THREAD

**Issue by paulgavrikov** [ajaysub110/critical-band-masking#1] opened 2023-11-02 01:04 UTC
Thank you for sharing the code! I am trying to reproduce the Gaussian fitting results and have a few questions regarding this:

1. In the Appendix you state an average BW of `1.44`. According to Table 1 the mean sigma is `0.66` and your formula in Appendix C states `BW=log2(2.355 * sigma)` which would be `0.63`. What am I missing here? 
2. Similarly, `mu` in Table 1 != `center frequency` in Table A. How do I convert it into the center frequency? The amplitude seems fine.
3. Using `human_analysis.ipynb` I tried to reproduce the average human heatmap. I assume there is some error in the NB and you want to change `ax.imshow(accuracy_matrix)` to `ax.imshow(final_mat)`. However, even then the heatmap is slightly different. What's the difference?
4. If I fit the Gaussian to `final_mat` and change the threshold to 50% (I assume that is what you use for the results in the paper and not 60% as in the NB?) I get the following `bw, mean, height = (0.9999775891791427, 4.499999999997049, 3.999999995574868)` which according to your formulas would be `log2(BW)=2^1=2`, `CF=4.5`, and `PNS=1/(0.02*(2^3.999999995574868))=3.125`. All these numbers are way off. What am I doing wrong?

**Comment by ajaysub110** [comment] 2023-11-02 17:01
Hi Paul,

Thank you for pointing out these important issues. The formulas for calculation of BW, CF and PNS, as written in the paper, are currently misleading and should be changed. Additionally, the error you point out in point 3 is an error in our results, and will also have to be changed in the paper and figures. These changes will not alter any of the conclusions of the paper, but they are nevertheless important. 

I have approached the NeurIPS program chairs with a request to make these changes to the paper, although the camera-ready deadline has already passed. If they allow us to make changes, I will also make sure to add you to our Acknowledgements. Thanks a lot!

Responding to your points below:

**Point 3**:
Just pushed a fix for this, using `final_mat` instead of `accuracy_matrix` and changed threshold to 50%. As I mentioned above, this will change all our human results, so I will make the appropriate changes to the paper.

**Point 4**:
The `bw, mean, height` values you report are the correct values (the paper is incorrect). The formulas used to calculate BW, CF, PNS from these are misleading, and will be fixed in the paper. Here are the correct formulas and values:

```
BW = bw = 0.999 ~ 1.000 octaves; bw = 2 * sqrt(ln 4) * sigma
CF = 1.75 * (2 ** mean) = 39.597 cycles/image
PNS = 1 / (0.02 * 2 ** A) = 3.125 per SD unit
```

**Points 1, 2**:
Table A in the Appendix is confusing. The average BW, CF, and PNS reported there are what you get when metrics are calculated from separate Gaussian fits to each observer, and then averaged. The parameters for humans reported in Table 1 is when we fit the Gaussian to the average accuracy matrix of all observers, which is what we use for the main paper. I will replace Table A in the paper with values from Table 1 to avoid this confusion.

The mean sigma in table 1, as mentioned above, is incorrect. It should be `0.4246`. And then using the formula for BW written above, you will get ~ 1.000 octaves. Please note that this will not change our conclusion of the one-octave wide human channel. In fact, its actually closer to 1 now.

Thank you again for pointing out all these issues, and I'm sorry there are so many! Please let me know if you face any other issues with the code.

Over the next week, I plan to add some more of the analysis code so stuff is easier to reproduce, specially for networks.

Ajay

**Comment by paulgavrikov** [comment] 2023-11-05 16:07
Thank you so much for the clarification and your honesty! 

I have another question regarding the evaluation of models. Would you use the same code to evaluate the network results? I am asking because AT models are highly susceptible to contrast changes, and their baseline acc on the non-noisy dataset would already be significantly impaired. Not normalizing the accuracy by the baseline on CBM would result in some cases where the entire heatmap would be < 50%. 

E.g. see attached examples for a less extreme case (`l2, eps=0.5`): 

Not normalized:

> channel_props:
> BW: 13.04 octaves,
> CF: 11.79 cycles/image,
> PNS: 0.97 per unit SD

Normalized by the maximum acc in the heatmap (as a non-ideal proxy).

> channel_props:
> BW: 4.41 octaves,
> CF: 30.61 cycles/image,
> PNS: 0.97 per unit SD

I've also visualized the resulting 50% masks. By normalizing the accuracy, the results appear to be quite similar to a non-AT R50. I know you discuss in Appendix F that normalization does not significantly affect results and this is probably the case on non-At models (which are the majority of your model zoo), but have you verified this on AT models?

![b9e7a21d-8e62-4581-bb02-9919d208d575](https://github.com/ajaysub110/critical-band-masking/assets/9333587/1037cc95-a4fa-4d6a-bc6f-bebb47776f4e)

![c160e8b8-c20d-4afc-8591-e33911be9703](https://github.com/ajaysub110/critical-band-masking/assets/9333587/552b3524-c5b7-4f35-80ad-2efa5cf6d1d2)

**Comment by ajaysub110** [comment] 2023-11-05 16:41
We used the same evaluation method for all networks that were more than 50% accurate for the baseline (no-noise, 20% contrast condition). This meant that we had to discard some networks from our critical-band-masking analysis (e.g., adv-nets with eps=3,5; see Fig. 4 of appendix). 

Yes, if you normalize heatmaps, you'll get smaller bandwidths for some of the adversarial networks, but as I state in section F of appendix, we don't do that because that's an unfair comparison between networks, i.e. the scale for their thresholds will be different. 

Good models of human behavior should be robust to noise, so if adding a very small amount of noise brings them below 50% accuracy, we treat them like they are affected by noise at all bands. I agree that this isn't as clean of a result as the non-adv-nets, but until we come up with a normalized metric that is scale invariant, we thought this would be reasonable to use. Thank you for pointing it out though!

**Comment by paulgavrikov** [comment] 2023-11-05 17:23
Thanks for the swift answer! I understand your reasoning and I see pros and cons for both approaches. It's still worth noting, though, that your observed trends on AT models are less obvious under normalization (computed on your json files).
![image](https://github.com/ajaysub110/critical-band-masking/assets/9333587/6816d610-1958-4868-8425-3fd3259e04c7)

**Closed as completed** 2023-12-01 05:31 UTC
